# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="cloud"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

plugins=(debian node git git-extras colored-man zsh_reload dirhistory)

source $ZSH/oh-my-zsh.sh

#yes, I suck.
export EDITOR='nano -w'

# The next line updates PATH for the Google Cloud SDK.
source /google-cloud-sdk/path.zsh.inc

# The next line enables bash completion for gcloud.
source /google-cloud-sdk/completion.zsh.inc

#add appengine to the path
export PATH=/go_appengine:$GOPATH/bin:/usr/src/go/bin:$PATH